### ISSUE TITLE
Commit composer.lock to git

### ISSUE THREAD

**Issue by deevus** [Mezzle/grumphp-tasks#11]
See https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by deevus** [comment]
A bit further down it says this:

> For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by Mezzle** [comment]
Thanks for this contribution!

I'd always considered the `composer.lock` as something that might get in the way of others in the case of a library.  Thanks for pointing this out - I'm now wondering how many other projects I should go back to and commit the `composer.lock`

My only concern really would be managing the changes for this - and having people using different versions of PHP when they're developing on it
