### ISSUE TITLE
The option "bin" does not exist. Defined options are: "config", "debug".

### ISSUE THREAD

**Issue by deevus** [Mezzle/grumphp-tasks#9]
To reproduce: set the `bin` configuration. 

Introduced here: https://github.com/Mezzle/grumphp-tasks/commit/09283a8bc3871e7cd0198e1483e5b7b947bfd8bc

This was my commit, however it was not tested on this fork of the repo. 

Solution: Need to add `bin` as an allowed configuration parameter.

**Comment by Mezzle** [comment]
Thanks for raising this! 

Feel free to open these as PRs directly, no need for the separate issue!

Really appreciate the contributions!  I've made sure that I'm now actually watching this.

I've pushed a new tag with a patch revision so this should be available as an update via packagist

**Comment by deevus** [comment]
Cool. Thanks for that :)
